### ISSUE TITLE
Comply with RDF Turtle syntax

### ISSUE THREAD

**Issue by prohde** [rdfshapes/shacl-sparql#2]
Please comply with RDF Turtle syntax.

From the [documentation](https://www.w3.org/TR/turtle/#sec-iri) (right above 2.5) it reads:

> The '@prefix' and '@base' directives require a trailing '.' after the IRI, the equalivent 'PREFIX' and 'BASE' must not have a trailing '.' after the IRI part of the directive.

Therefore the shapes in Turtle format should have a trailing '.' after the IRI:

```
@prefix dbo: <http://dbpedia.org/ontology/> .
@prefix dbr: <http://dbpedia.org/resource/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix : <http://example.org/> .
```

**Comment by juliencorman** [comment]
Thank you for the pointer.
These are correctly parsed by the Shaclex API (which itself depends on Jena), but I added the period anyway (commit 5d68f34).
