### ISSUE TITLE
Provide all shapes in RDF Turtle syntax

### ISSUE THREAD

**Issue by prohde** [rdfshapes/shacl-sparql#3]
Please add all shapes in Turtle syntax also for better understanding of the shapes used.
I was not able to understand all shapes in JSON format even with the provided documentation.

**Comment by juliencorman** [comment]
I converted the shapes in JSON format to RDF (commit 5d68f34).

The non-recursive schemas can be found in "ex/shapes/nonRec", and the recursive schemas in "ex/shapes/rec".
